### ISSUE TITLE
GunGame: Heavy lags to server

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#190]
Whenever GunGame is played, server with 12+ players can starts to cause heavy lags to the server, and gets worse over time.

It said that it might be to do with the rank code, aka switching player class and weapon

**Comment by xMasterDizzy** [comment]
It is pretty weird because GunGame wasn't laggy at all a few months ago.
The problem must be inside of some piece of code that was added to the gamemode lately.
Or maybe TF2 is THE PROBLEM, but I really doubt it.

**Comment by ramunecarbonated** [comment]
commit https://github.com/EgocentricPoliceDick/GunGame/commit/ec38ba6dae8faa00a04231efef294a0e977796b8 should fix this, there is a line of code I added a long time ago that loops through all wearables on the server upon level up and kills the wearables of the client, if it doesn't work just post here again and I will be notified.

currently working on szf but a gg rewrite is coming

**Comment by EgocentricPoliceDick** [comment]
I'll mark this as closed then. Please comment if issue still occurs.

**Comment by itVictor** [comment]
bumping as the lag is still there, currently getting massive lag on raiden during gg

**Comment by EgocentricPoliceDick** [comment]
I should probably update this:
GunGame is currently disabled from appearing in the public vote until this issue is fixed because of the severity of it.

**Comment by ramunecarbonated** [comment]
still no solution on it, fyi. probably gonna take a rewrite and hopefully it will be fixed when that is done.
