### ISSUE TITLE
koth_aurora_mansion_v4_rs: The secret room badge is not being awarded

### ISSUE THREAD

**Issue by haxtonsale** [redsunservers/LoadoutBugTracker#221]
Basically, one lad got into the secret room on aurora mansion and didn't get the badge. 
Happened on Armstrong and Maverick, not sure if Raiden has the same issue.

**Comment by ramunecarbonated** [comment]
Did the person in question have a Loadout account?

**Comment by haxtonsale** [comment]
Yes

**Comment by ramunecarbonated** [comment]
@koopa516 if you fix this fix the loadout strange count on all slots function too finally thank you ❤️

**Comment by koopa516** [comment]
fixed

**Comment by haxtonsale** [comment]
The badge is still broken btw, tested on Armstrong and Raiden

**Comment by koopa516** [comment]
actually fixed this time; I'd forgotten to upload a file on maverick, plus the zones weren't named properly on the other servers.
