### ISSUE TITLE
Outdated info in !hop and chat ads

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#265]
maverick/mistral still listed as LA

<img width="337" alt="screen shot 2018-07-30 at 7 16 42 pm" src="https://user-images.githubusercontent.com/20176719/43430191-4b732516-942d-11e8-82c4-677323e6cb71.png">

<img width="340" alt="screen shot 2018-07-30 at 7 16 32 pm" src="https://user-images.githubusercontent.com/20176719/43430194-4d5577c6-942d-11e8-80c6-a6f2b7ce7f22.png">

**Comment by EgocentricPoliceDick** [comment]
fixed, update will apply over the next few hours

**Comment by itVictor** [comment]
bumping as issue is still occuring on raiden (only on raiden, shows correct information if you do !hop on other servers)
<img width="317" alt="screen shot 2018-12-27 at 5 17 32 pm" src="https://user-images.githubusercontent.com/20176719/50497258-8d164900-09fb-11e9-987a-8866acffa834.png">
