### ISSUE TITLE
Taunt 531 has an invalid sample rate

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#297]
(I don't know what it's called, sorry)

When it tries to be played, console prints out this error:

> *** Invalid sample rate (32000) for sound 'redsun\items\taunt\531.mp3'.

as usual, here's a quick fix for it: https://cdn.discordapp.com/attachments/332809334339665930/507275148676562945/531_fix.mp3

**Comment by EgocentricPoliceDick** [comment]
I'll get round to this once we get the big issues right now fixed.

**Comment by haxtonsale** [comment]
Same for 526 and 521 so i fixed em
https://cdn.discordapp.com/attachments/411926809920274444/507278419835486241/526.mp3
https://cdn.discordapp.com/attachments/411926809920274444/507278409940860929/521.mp3

Didn't know that 32k hz wasn't good for source 🤔

**Comment by woisalreadytaken** [comment]
the items (at least jouster's entrance banner sound and kirov reporting respawn, not sure about welcome to my inn because I don't have the taunt) still don't play but now no errors show up, like how the retired hermit wasn't playing anything before yesterday

**Comment by haxtonsale** [comment]
Apparently, the "Welcome to my inn" item is still not working.
