### ISSUE TITLE
vsh: shield sometimes not breaking 

### ISSUE THREAD

**Issue by retardsrock** [redsunservers/LoadoutBugTracker#382]
Sometimes on vsh hale damages you instead of breaking your shield.
the glitch isn't that bad but its just unfair as hell.
sadly i do not know how to reproduce the glitch.

**Comment by FortyTwoFortyTwo** [comment]
Going to try use another method into detecting whenever if it a melee attack or not, who knows if i broke something else during that

**Comment by FortyTwoFortyTwo** [comment]
Bug still exists

**Comment by FortyTwoFortyTwo** [comment]
Really don't have a clue why this "randomly" happens, need more help/info from someone who can keep getting this problem

**Comment by FortyTwoFortyTwo** [comment]
Should be fixed for real.

If anyone interested how it happened, shield only breaks if it a melee hit, where weapon index and class is needed to know which slot is used to attack.
But for Saxton Hale, fists for heavy while playing as soldier, slot could not be found. So i have to use a different method for this.

**Comment by infinitephantasm** [comment]
bug still occurring, however the only demo i have of it happening was on a workshop map so i can't exactly see what happened

all i know is that saxton hale punched me when i had enough health to survive, but i didn't lose my shield

**Comment by FortyTwoFortyTwo** [comment]
Works fine for me, tested with Tide Turner and Razorback against Saxton Hale, need more info

**Comment by FortyTwoFortyTwo** [comment]
Haven't heard anything new about this, or anyone else have this problem in the past month.
Going to assume this bug somehow went gone.

**Comment by FortyTwoFortyTwo** [comment]
I'm wrong, still somehow exists.
Also said it only happens if healed, somewhat similar to #400

**Comment by FortyTwoFortyTwo** [comment]
Fixed, more details here
https://github.com/redsunservers/LoadoutBugTracker/issues/400#issuecomment-519289285
